### ISSUE TITLE
Redis memory leak risk in PhysicalEntityCacheUpdater

### ISSUE THREAD

**Issue by yejianquan** [sonic-net/sonic-snmpagent#342]
**Description**

**Steps to reproduce the issue:**
1. Start the snmp docker container
2. Trigger a never auto-recovered error in any of the physical_entity_updater, for example: Remove the key in state db: `PHYSICAL_ENTITY_INFO|PSU 2`, this will cause ValueError, because it tries to cast a empty string to int value
```
2024 Dec 13 08:32:42.100531 x-sup-2 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.11/dist-packages/ax_interface/mib.py", line 45, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 323, in reinit_data#012    updater.reinit_data()#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 664, in reinit_data#012    self._update_entity_cache(name)#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 865, in _update_entity_cache#012    psu_position = int(psu_position)#012     
```
3. The omem of the redis client starts to increase slowly, some output from my test script:
```
Iteration: 26
ASIC: 0, total_omem: 0, result: False
ASIC: 1, total_omem: 0, result: False
ASIC: 4, total_omem: 0, result: False
ASIC: 5, total_omem: 0, result: False
ASIC: 8, total_omem: 0, result: False
ASIC: 9, total_omem: 0, result: False
ASIC: 10, total_omem: 0, result: False
ASIC: 11, total_omem: 0, result: False
ASIC: 12, total_omem: 0, result: False
ASIC: 13, total_omem: 0, result: False
Sleep 5 seconds
---------------------------------------------------------------------------------
Iteration: 27
ASIC: 0, total_omem: 20504, result: False
ASIC: 1, total_omem: 20504, result: False
ASIC: 4, total_omem: 20504, result: False
ASIC: 5, total_omem: 20504, result: False
ASIC: 8, total_omem: 20504, result: False
ASIC: 9, total_omem: 20504, result: False
ASIC: 10, total_omem: 20504, result: False
ASIC: 11, total_omem: 20504, result: False
ASIC: 12, total_omem: 20504, result: False
ASIC: 13, total_omem: 20504, result: False
Sleep 5 seconds
---------------------------------------------------------------------------------

...

---------------------------------------------------------------------------------
Iteration: 83
ASIC: 0, total_omem: 225544, result: False
ASIC: 1, total_omem: 225544, result: False
ASIC: 4, total_omem: 225544, result: False
ASIC: 5, total_omem: 225544, result: False
ASIC: 8, total_omem: 225544, result: False
ASIC: 9, total_omem: 225544, result: False
ASIC: 10, total_omem: 225544, result: False
ASIC: 11, total_omem: 225544, result: False
ASIC: 12, total_omem: 225544, result: False
ASIC: 13, total_omem: 225544, result: False
Sleep 5 seconds
---------------------------------------------------------------------------------
Iteration: 84
ASIC: 0, total_omem: 225544, result: False
ASIC: 1, total_omem: 225544, result: False
ASIC: 4, total_omem: 225544, result: False
ASIC: 5, total_omem: 225544, result: False
ASIC: 8, total_omem: 225544, result: False
ASIC: 9, total_omem: 225544, result: False
ASIC: 10, total_omem: 225544, result: False
ASIC: 11, total_omem: 225544, result: False
ASIC: 12, total_omem: 225544, result: False
ASIC: 13, total_omem: 225544, result: False
Sleep 5 seconds
---------------------------------------------------------------------------------
```

**Describe the results you received:**
The redis memory gradually increase, have to restart snmp docker container to clear it.

**Describe the results you expected:**
Redis memory should not leak.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yejianquan** [comment]
one of the RCA of https://github.com/sonic-net/sonic-buildimage/issues/20680

**Comment by yejianquan** [comment]
Detailed RCA of this issue in the comments of https://github.com/sonic-net/sonic-snmpagent/pull/343
